In [2]:
import cv2
import numpy as np

In [78]:
def code_check():
    # Read image 
    img = cv2.imread('src/one_note.png', cv2.IMREAD_COLOR) # road.png is the filename
    img_shape = 200
    img = cv2.resize(img, dsize=(img_shape, int(img_shape/img.shape[1] * img.shape[0])))
    result = img.copy()
    # Convert the image to gray-scale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, gray = cv2.threshold(gray, 220, 255, cv2.THRESH_BINARY_INV)
    # Find the edges in the image using canny detector
#     edges = cv2.Canny(gray, 50, 200)
#     cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
    # Detect points that form a line
    cv2.imshow("", gray)
    lines = cv2.HoughLinesP(gray, 1, np.pi/2, 100, maxLineGap=15)
    print(lines)
    # Draw lines on the image
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            cv2.line(result, (x1, y1), (x2, y2), (255, 0, 0), 1)
    # Show result
    cv2.imshow("Original", img)
    cv2.imshow("Result Image", result)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


def test():
    SRC_PATH = 'src/'
    image_width = 600
    image_height = 800

    filename = SRC_PATH + "one_note.png"
    image = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
    # padding_x = (image_width - image.shape[1])//2
    # padding_y = (image_height - image.shape[0])//2
    # image = cv2.copyMakeBorder(image, padding_y, padding_y, padding_x, padding_x, cv2.BORDER_CONSTANT, value=255)
    result = cv2.Sobel(image, cv2.CV_16S, 0, 1, ksize=1)
    result = np.absolute(result).astype(np.uint8)
    
    cv2.imshow("Original", image)
    cv2.imshow("Result", result)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [79]:
code_check()

[[[103 244 103  45]]

 [[107 244 107  42]]

 [[115 212 115  43]]

 [[  0 132 199 132]]

 [[  0 296 199 296]]

 [[  0 235 199 235]]

 [[  0 295 199 295]]

 [[102 244 102  47]]

 [[  0 189 199 189]]

 [[  0 291 199 291]]

 [[  0 131 199 131]]

 [[  0 186 199 186]]

 [[  0 287 199 287]]

 [[104 244 104  44]]

 [[  0 286 199 286]]

 [[  0 184 199 184]]

 [[  0 193 199 193]]

 [[  0 288 199 288]]

 [[  0 237 199 237]]

 [[  0 293 199 293]]

 [[  0 290 199 290]]

 [[  0 137 199 137]]

 [[  0 191 199 191]]

 [[  0 294 199 294]]

 [[  0 134 199 134]]

 [[  0 133 199 133]]

 [[  0 185 199 185]]

 [[  0  89 199  89]]

 [[  0 187 199 187]]

 [[  0 243 199 243]]

 [[  0 136 199 136]]

 [[  0 190 199 190]]

 [[  0 236 199 236]]

 [[  0  88 199  88]]

 [[  0  84 199  84]]

 [[  0 242 199 242]]

 [[  0  82 199  82]]

 [[  0 188 199 188]]

 [[  0 192 199 192]]

 [[  0 183 199 183]]

 [[  0  83 199  83]]

 [[  0 238 199 238]]

 [[  0 292 199 292]]

 [[  0  80 199  80]]

 [[  0 289 199 289]]

 [[  0  86